/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: LPC54608J512
package_id: LPC54608J512ET180
mcu_data: ksdk2_0
processor_version: 3.0.1
board: LPCXpresso54608
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

#define IOCON_PIO_DIGITAL_EN        0x0100u   /*!< Enables digital function */
#define IOCON_PIO_FUNC1               0x01u   /*!< Selects pin function 1 */
#define IOCON_PIO_FUNC2               0x02u   /*!< Selects pin function 2 */
#define IOCON_PIO_FUNC5               0x05u   /*!< Selects pin function 2 */

#define IOCON_PIO_INPFILT_OFF       0x0200u   /*!< Input filter disabled */
#define IOCON_PIO_INV_DI              0x00u   /*!< Input function is not inverted */
#define IOCON_PIO_MODE_INACT          0x00u   /*!< No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI        0x00u   /*!< Open drain is disabled */
#define IOCON_PIO_SLEW_FAST         0x0400u   /*!< Fast mode, slew rate control is disabled */
#define IOCON_PIO_SLEW_STANDARD       0x00u   /*!< Standard mode, output slew rate control is enabled */
#define PIN3_IDX                         3u   /*!< Pin number for pin 3 in a port 2 */
#define PIN4_IDX                         4u   /*!< Pin number for pin 4 in a port 2 */
#define PIN5_IDX                         5u   /*!< Pin number for pin 5 in a port 2 */
#define PIN6_IDX                         6u   /*!< Pin number for pin 6 in a port 2 */
#define PIN7_IDX                         7u   /*!< Pin number for pin 7 in a port 2 */
#define PIN8_IDX                         8u   /*!< Pin number for pin 8 in a port 2 */
#define PIN9_IDX                         9u   /*!< Pin number for pin 9 in a port 2 */
#define PIN10_IDX                       10u   /*!< Pin number for pin 10 in a port 2 */
#define PIN15_IDX                       15u   /*!< Pin number for pin 15 in a port 3 */
#define PIN29_IDX                       29u   /*!< Pin number for pin 29 in a port 0 */
#define PIN30_IDX                       30u   /*!< Pin number for pin 30 in a port 0 */
#define PORT0_IDX                        0u   /*!< Port index */
#define PORT2_IDX                        2u   /*!< Port index */
#define PORT3_IDX                        3u   /*!< Port index */


#define IOCON_PIO_MODE_PULLUP 0x20u    /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_EN 0x0800u /*!<@brief Open drain is enabled */

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_30/FC0_TXD_SCL_MISO/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA(1), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: B13, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA(2), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: D6, peripheral: FLEXCOMM3, signal: SCK, pin_signal: PIO0_0/CAN1_RD/FC3_SCK/CTIMER0_MAT0/SCT0_GPI0/PDM0_CLK, mode: pullUp, invert: disabled, glitch_filter: disabled,
    slew_rate: standard, open_drain: disabled}
  - {pin_num: A1, peripheral: FLEXCOMM3, signal: CTS_SDA_SSEL0, pin_signal: PIO0_1/CAN1_TD/FC3_CTS_SDA_SSEL0/CTIMER0_CAP0/SCT0_GPI1/PDM0_DATA, mode: pullUp, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: E9, peripheral: FLEXCOMM3, signal: TXD_SCL_MISO, pin_signal: PIO0_2/FC3_TXD_SCL_MISO/CTIMER0_CAP1/SCT0_OUT0/SCT0_GPI2/EMC_D(0), mode: pullUp, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: A10, peripheral: FLEXCOMM3, signal: RXD_SDA_MOSI, pin_signal: PIO0_3/FC3_RXD_SDA_MOSI/CTIMER0_MAT1/SCT0_OUT1/SCT0_GPI3/EMC_D(1), mode: pullUp, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: N2, peripheral: FLEXCOMM9, signal: SCK, pin_signal: PIO3_20/FC9_SCK/SD_CARD_INT_N/CLKOUT/SCT0_OUT7, mode: pullUp, invert: disabled, glitch_filter: disabled,
    slew_rate: standard, open_drain: disabled}
  - {pin_num: P5, peripheral: FLEXCOMM9, signal: RXD_SDA_MOSI, pin_signal: PIO3_21/FC9_RXD_SDA_MOSI/SD_BACKEND_PWR/CTIMER4_MAT3/UTICK_CAP2/ADC0_9, mode: pullUp, invert: disabled,
    glitch_filter: disabled, open_drain: disabled}
  - {pin_num: N5, peripheral: FLEXCOMM9, signal: TXD_SCL_MISO, pin_signal: PIO3_22/FC9_TXD_SCL_MISO/ADC0_10, mode: pullUp, invert: disabled, glitch_filter: disabled,
    open_drain: disabled}
  - {pin_num: K13, peripheral: FLEXCOMM9, signal: CTS_SDA_SSEL0, pin_signal: PIO3_30/FC9_CTS_SDA_SSEL0/SCT0_OUT4/FC4_SSEL2/EMC_A(19), mode: pullUp, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */


void BOARD_InitPins(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    CLOCK_EnableClock(kCLOCK_InputMux);
    CLOCK_EnableClock(kCLOCK_Gpio0);
    CLOCK_EnableClock(kCLOCK_Gpio1);
    CLOCK_EnableClock(kCLOCK_Gpio2);
    CLOCK_EnableClock(kCLOCK_Gpio3);
    CLOCK_EnableClock(kCLOCK_Gpio4);
    CLOCK_EnableClock(kCLOCK_Gpio5);
/************************* SDRAM **************************/

    const uint32_t port0_pin15_config = (/* Pin is configured as EMC_WEN */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN15 (coords: L4) is configured as EMC_WEN */
        IOCON_PinMuxSet(IOCON, 0U, 15U, port0_pin15_config);

        const uint32_t port0_pin18_config = (/* Pin is configured as EMC_A(0) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN18 (coords: C14) is configured as EMC_A(0) */
        IOCON_PinMuxSet(IOCON, 0U, 18U, port0_pin18_config);

        const uint32_t port0_pin19_config = (/* Pin is configured as EMC_A(1) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN19 (coords: C6) is configured as EMC_A(1) */
        IOCON_PinMuxSet(IOCON, 0U, 19U, port0_pin19_config);

        const uint32_t port0_pin2_config = (/* Pin is configured as EMC_D(0) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN2 (coords: E9) is configured as EMC_D(0) */
        IOCON_PinMuxSet(IOCON, 0U, 2U, port0_pin2_config);

        const uint32_t port0_pin20_config = (/* Pin is configured as EMC_A(2) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN20 (coords: D13) is configured as EMC_A(2) */
        IOCON_PinMuxSet(IOCON, 0U, 20U, port0_pin20_config);

        const uint32_t port0_pin21_config = (/* Pin is configured as EMC_A(3) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN21 (coords: C13) is configured as EMC_A(3) */
        IOCON_PinMuxSet(IOCON, 0U, 21U, port0_pin21_config);


        const uint32_t port0_pin3_config = (/* Pin is configured as EMC_D(1) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN3 (coords: A10) is configured as EMC_D(1) */
        IOCON_PinMuxSet(IOCON, 0U, 3U, port0_pin3_config);

        const uint32_t port0_pin4_config = (/* Pin is configured as EMC_D(2) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN4 (coords: C8) is configured as EMC_D(2) */
        IOCON_PinMuxSet(IOCON, 0U, 4U, port0_pin4_config);

        const uint32_t port0_pin5_config = (/* Pin is configured as EMC_D(3) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN5 (coords: E7) is configured as EMC_D(3) */
        IOCON_PinMuxSet(IOCON, 0U, 5U, port0_pin5_config);

        const uint32_t port0_pin6_config = (/* Pin is configured as EMC_D(4) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN6 (coords: A5) is configured as EMC_D(4) */
        IOCON_PinMuxSet(IOCON, 0U, 6U, port0_pin6_config);

        const uint32_t port0_pin7_config = (/* Pin is configured as EMC_D(5) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN7 (coords: H12) is configured as EMC_D(5) */
        IOCON_PinMuxSet(IOCON, 0U, 7U, port0_pin7_config);

        const uint32_t port0_pin8_config = (/* Pin is configured as EMC_D(6) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN8 (coords: H10) is configured as EMC_D(6) */
        IOCON_PinMuxSet(IOCON, 0U, 8U, port0_pin8_config);

        const uint32_t port0_pin9_config = (/* Pin is configured as EMC_D(7) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN9 (coords: G12) is configured as EMC_D(7) */
        IOCON_PinMuxSet(IOCON, 0U, 9U, port0_pin9_config);

        const uint32_t port1_pin10_config = (/* Pin is configured as EMC_RASN */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN10 (coords: N9) is configured as EMC_RASN */
        IOCON_PinMuxSet(IOCON, 1U, 10U, port1_pin10_config);

        const uint32_t port1_pin11_config = (/* Pin is configured as EMC_CLK(0) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN11 (coords: B4) is configured as EMC_CLK(0) */
        IOCON_PinMuxSet(IOCON, 1U, 11U, port1_pin11_config);

        const uint32_t port1_pin12_config = (/* Pin is configured as EMC_DYCSN(0) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN12 (coords: K9) is configured as EMC_DYCSN(0) */
        IOCON_PinMuxSet(IOCON, 1U, 12U, port1_pin12_config);

        const uint32_t port1_pin13_config = (/* Pin is configured as EMC_DQM(0) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN13 (coords: G10) is configured as EMC_DQM(0) */
        IOCON_PinMuxSet(IOCON, 1U, 13U, port1_pin13_config);

        const uint32_t port1_pin14_config = (/* Pin is configured as EMC_DQM(1) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN14 (coords: C12) is configured as EMC_DQM(1) */
        IOCON_PinMuxSet(IOCON, 1U, 14U, port1_pin14_config);

        const uint32_t port1_pin15_config = (/* Pin is configured as EMC_CKE(0) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN15 (coords: A11) is configured as EMC_CKE(0) */
        IOCON_PinMuxSet(IOCON, 1U, 15U, port1_pin15_config);

        const uint32_t port1_pin16_config = (/* Pin is configured as EMC_A(10) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN16 (coords: B7) is configured as EMC_A(10) */
        IOCON_PinMuxSet(IOCON, 1U, 16U, port1_pin16_config);

        const uint32_t port1_pin19_config = (/* Pin is configured as EMC_D(8) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN19 (coords: L1) is configured as EMC_D(8) */
        IOCON_PinMuxSet(IOCON, 1U, 19U, port1_pin19_config);

        const uint32_t port1_pin20_config = (/* Pin is configured as EMC_D(9) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN20 (coords: M1) is configured as EMC_D(9) */
        IOCON_PinMuxSet(IOCON, 1U, 20U, port1_pin20_config);

        const uint32_t port1_pin21_config = (/* Pin is configured as EMC_D(10) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN21 (coords: N8) is configured as EMC_D(10) */
        IOCON_PinMuxSet(IOCON, 1U, 21U, port1_pin21_config);

        const uint32_t port1_pin23_config = (/* Pin is configured as EMC_A(11) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN23 (coords: M10) is configured as EMC_A(11) */
        IOCON_PinMuxSet(IOCON, 1U, 23U, port1_pin23_config);

        const uint32_t port1_pin24_config = (/* Pin is configured as EMC_A(12) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN24 (coords: N14) is configured as EMC_A(12) */
        IOCON_PinMuxSet(IOCON, 1U, 24U, port1_pin24_config);

        const uint32_t port1_pin25_config = (/* Pin is configured as EMC_A(13) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN25 (coords: M12) is configured as EMC_A(13) */
        IOCON_PinMuxSet(IOCON, 1U, 25U, port1_pin25_config);

        const uint32_t port1_pin26_config = (/* Pin is configured as EMC_A(8) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN26 (coords: J10) is configured as EMC_A(8) */
        IOCON_PinMuxSet(IOCON, 1U, 26U, port1_pin26_config);

        const uint32_t port1_pin27_config = (/* Pin is configured as EMC_A(9) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN27 (coords: F10) is configured as EMC_A(9) */
        IOCON_PinMuxSet(IOCON, 1U, 27U, port1_pin27_config);

        const uint32_t port1_pin28_config = (/* Pin is configured as EMC_D(12) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN28 (coords: E12) is configured as EMC_D(12) */
        IOCON_PinMuxSet(IOCON, 1U, 28U, port1_pin28_config);

        const uint32_t port1_pin29_config = (/* Pin is configured as EMC_D(13) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN29 (coords: C11) is configured as EMC_D(13) */
        IOCON_PinMuxSet(IOCON, 1U, 29U, port1_pin29_config);

        const uint32_t port1_pin30_config = (/* Pin is configured as EMC_D(14) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN30 (coords: A8) is configured as EMC_D(14) */
        IOCON_PinMuxSet(IOCON, 1U, 30U, port1_pin30_config);

        const uint32_t port1_pin31_config = (/* Pin is configured as EMC_D(15) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN31 (coords: C5) is configured as EMC_D(15) */
        IOCON_PinMuxSet(IOCON, 1U, 31U, port1_pin31_config);

        const uint32_t port1_pin4_config = (/* Pin is configured as EMC_D(11) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN4 (coords: D4) is configured as EMC_D(11) */
        IOCON_PinMuxSet(IOCON, 1U, 4U, port1_pin4_config);

        const uint32_t port1_pin5_config = (/* Pin is configured as EMC_A(4) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN5 (coords: E4) is configured as EMC_A(4) */
        IOCON_PinMuxSet(IOCON, 1U, 5U, port1_pin5_config);

        const uint32_t port1_pin6_config = (/* Pin is configured as EMC_A(5) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN6 (coords: G4) is configured as EMC_A(5) */
        IOCON_PinMuxSet(IOCON, 1U, 6U, port1_pin6_config);

        const uint32_t port1_pin7_config = (/* Pin is configured as EMC_A(6) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN7 (coords: N1) is configured as EMC_A(6) */
        IOCON_PinMuxSet(IOCON, 1U, 7U, port1_pin7_config);

        const uint32_t port1_pin8_config = (/* Pin is configured as EMC_A(7) */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN8 (coords: P8) is configured as EMC_A(7) */
        IOCON_PinMuxSet(IOCON, 1U, 8U, port1_pin8_config);

        const uint32_t port1_pin9_config = (/* Pin is configured as EMC_CASN */
                                            IOCON_PIO_FUNC6 |
                                            /* No addition pin function */
                                            IOCON_PIO_MODE_INACT |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Input filter disabled */
                                            IOCON_PIO_INPFILT_OFF |
                                            /* Fast mode, slew rate control is disabled */
                                            IOCON_PIO_SLEW_FAST |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN9 (coords: K6) is configured as EMC_CASN */
        IOCON_PinMuxSet(IOCON, 1U, 9U, port1_pin9_config);

        IOCON->PIO[2][18] = ((IOCON->PIO[2][18] &
                              /* Mask bits to zero which are setting */
                              (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                             /* Selects pin function.: PORT218 (pin N10) is configured as FC3_RXD_SDA_MOSI */
                             | IOCON_PIO_FUNC(PIO218_FUNC_ALT2)

                             /* Select Analog/Digital mode.: Digital mode. */
                             | IOCON_PIO_DIGIMODE(PIO218_DIGIMODE_DIGITAL));

        IOCON->PIO[2][19] = ((IOCON->PIO[2][19] &
                              /* Mask bits to zero which are setting */
                              (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                             /* Selects pin function.: PORT219 (pin P12) is configured as FC3_TXD_SCL_MISO */
                             | IOCON_PIO_FUNC(PIO219_FUNC_ALT2)

                             /* Select Analog/Digital mode.: Digital mode. */
                             | IOCON_PIO_DIGIMODE(PIO219_DIGIMODE_DIGITAL));

        const uint32_t port3_pin25_config = (/* Pin is configured as EMC_A(14) */
                                             IOCON_PIO_FUNC6 |
                                             /* No addition pin function */
                                             IOCON_PIO_MODE_INACT |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Fast mode, slew rate control is disabled */
                                             IOCON_PIO_SLEW_FAST |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT3 PIN25 (coords: P9) is configured as EMC_A(14) */
        IOCON_PinMuxSet(IOCON, 3U, 25U, port3_pin25_config);


    const uint32_t port3_pin20_config = (/* Pin is configured as FC9_SCK */
                                         IOCON_PIO_FUNC1 |
                                         /* Selects pull-up function */
                                         IOCON_PIO_MODE_PULLUP |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT3 PIN20 (coords: N2) is configured as FC9_SCK */
    IOCON_PinMuxSet(IOCON, 3U, 20U, port3_pin20_config);

    const uint32_t port3_pin21_config = (/* Pin is configured as FC9_RXD_SDA_MOSI */
                                         IOCON_PIO_FUNC1 |
                                         /* Selects pull-up function */
                                         IOCON_PIO_MODE_PULLUP |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT3 PIN21 (coords: P5) is configured as FC9_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 3U, 21U, port3_pin21_config);

    const uint32_t port3_pin22_config = (/* Pin is configured as FC9_TXD_SCL_MISO */
                                         IOCON_PIO_FUNC1 |
                                         /* Selects pull-up function */
                                         IOCON_PIO_MODE_PULLUP |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT3 PIN22 (coords: N5) is configured as FC9_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 3U, 22U, port3_pin22_config);

    const uint32_t port3_pin30_config = (/* Pin is configured as FC9_CTS_SDA_SSEL0 */
                                         IOCON_PIO_FUNC1 |
                                         /* Selects pull-up function */
                                         IOCON_PIO_MODE_PULLUP |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT3 PIN30 (coords: K13) is configured as FC9_CTS_SDA_SSEL0 */
    IOCON_PinMuxSet(IOCON, 3U, 30U, port3_pin30_config);


    const uint32_t port3_pin27_config = (/* Pin is configured as FC9_SCK */
                                         IOCON_PIO_FUNC1 |
                                         /* Selects pull-up function */
                                         IOCON_PIO_MODE_PULLUP |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT3 PIN20 (coords: N2) is configured as FC9_SCK */
    IOCON_PinMuxSet(IOCON, 3U, 27U, port3_pin27_config);

//#ifdef SD___
    /************* SD CARD **********************/
      const uint32_t port2_pin10_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_CARD_DET_N */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN10_IDX, port2_pin10_config); /* PORT2 PIN10 (coords: P1) is configured as SD_CARD_DET_N */
      const uint32_t port2_pin3_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_CLK */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN3_IDX, port2_pin3_config); /* PORT2 PIN3 (coords: B1) is configured as SD_CLK */
      const uint32_t port2_pin4_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_CMD */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN4_IDX, port2_pin4_config); /* PORT2 PIN4 (coords: D3) is configured as SD_CMD */
      const uint32_t port2_pin5_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_POW_EN */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN5_IDX, port2_pin5_config); /* PORT2 PIN5 (coords: C1) is configured as SD_POW_EN */
      const uint32_t port2_pin6_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_D(0) */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN6_IDX, port2_pin6_config); /* PORT2 PIN6 (coords: F3) is configured as SD_D(0) */
      const uint32_t port2_pin7_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_D(1) */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN7_IDX, port2_pin7_config); /* PORT2 PIN7 (coords: J2) is configured as SD_D(1) */
      const uint32_t port2_pin8_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_D(2) */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN8_IDX, port2_pin8_config); /* PORT2 PIN8 (coords: F4) is configured as SD_D(2) */
      const uint32_t port2_pin9_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_D(3) */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_FAST |                                    /* Fast mode, slew rate control is disabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN9_IDX, port2_pin9_config); /* PORT2 PIN9 (coords: K2) is configured as SD_D(3) */
      const uint32_t port3_pin15_config = (
        IOCON_PIO_FUNC2 |                                        /* Pin is configured as SD_WR_PRT */
        IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
        IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
        IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
        IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
        IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
        IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
      );
      IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN15_IDX, port3_pin15_config); /* PORT3 PIN15 (coords: D2) is configured as SD_WR_PRT */

//#endif



      const uint32_t port3_pin23_config = (/* Pin is configured as FC2_CTS_SDA_SSEL0 */
                                           IOCON_PIO_FUNC1 |
                                           /* I2C mode */
                                           IOCON_PIO_I2CSLEW_I2C |
                                           /* Input function is not inverted */
                                           IOCON_PIO_INV_DI |
                                           /* Enables digital function */
                                           IOCON_PIO_DIGITAL_EN |
                                           /* Input filter disabled */
                                           IOCON_PIO_INPFILT_OFF |
                                           /* High drive: 20 mA */
                                           IOCON_PIO_I2CDRIVE_HIGH |
                                           /* I2C 50 ns glitch filter enabled */
                                           IOCON_PIO_I2CFILTER_EN);
      /* PORT3 PIN23 (coords: C2) is configured as FC2_CTS_SDA_SSEL0 */
      IOCON_PinMuxSet(IOCON, 3U, 23U, port3_pin23_config);

      const uint32_t port3_pin24_config = (/* Pin is configured as FC2_RTS_SCL_SSEL1 */
                                           IOCON_PIO_FUNC1 |
                                           /* I2C mode */
                                           IOCON_PIO_I2CSLEW_I2C |
                                           /* Input function is not inverted */
                                           IOCON_PIO_INV_DI |
                                           /* Enables digital function */
                                           IOCON_PIO_DIGITAL_EN |
                                           /* Input filter disabled */
                                           IOCON_PIO_INPFILT_OFF |
                                           /* High drive: 20 mA */
                                           IOCON_PIO_I2CDRIVE_HIGH |
                                           /* I2C 50 ns glitch filter enabled */
                                           IOCON_PIO_I2CFILTER_EN);
      /* PORT3 PIN24 (coords: E2) is configured as FC2_RTS_SCL_SSEL1 */
      IOCON_PinMuxSet(IOCON, 3U, 24U, port3_pin24_config);



      const uint32_t port0_pin10_config = (/* Pin is configured as SWO */
                                              IOCON_PIO_FUNC6 |
                                              /* No addition pin function */
                                              IOCON_PIO_MODE_INACT |
                                              /* Input function is not inverted */
                                              IOCON_PIO_INV_DI |
                                              /* Enables digital function */
                                              IOCON_PIO_DIGITAL_EN |
                                              /* Input filter disabled */
                                              IOCON_PIO_INPFILT_OFF |
                                              /* Open drain is disabled */
                                              IOCON_PIO_OPENDRAIN_DI);
         /* PORT0 PIN10 (coords: P2) is configured as SWO */
         IOCON_PinMuxSet(IOCON, 0U, 10U, port0_pin10_config);


         /* i2s */
         const uint32_t port4_pin1_config = (/* Pin is configured as FC6_SCK */
                                             IOCON_PIO_FUNC2 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
         /* PORT4 PIN1 (coords: G14) is configured as FC6_SCK */
         IOCON_PinMuxSet(IOCON, 4U, 1U, port4_pin1_config);

         const uint32_t port4_pin2_config = (/* Pin is configured as FC6_RXD_SDA_MOSI_DATA */
                                             IOCON_PIO_FUNC2 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
         /* PORT4 PIN2 (coords: F14) is configured as FC6_RXD_SDA_MOSI_DATA */
         IOCON_PinMuxSet(IOCON, 4U, 2U, port4_pin2_config);

         const uint32_t port4_pin3_config = (/* Pin is configured as FC6_TXD_SCL_MISO_WS */
                                             IOCON_PIO_FUNC2 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Input filter disabled */
                                             IOCON_PIO_INPFILT_OFF |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
         /* PORT4 PIN3 (coords: F13) is configured as FC6_TXD_SCL_MISO_WS */
         IOCON_PinMuxSet(IOCON, 4U, 3U, port4_pin3_config);


         //accelerometer
          const uint32_t port2_pin0_config = (/* Pin is configured as FC8_RXD_SDA_MOSI */
                                                   IOCON_PIO_FUNC2 |
                                                   /* Selects pull-up function */
                                                   IOCON_PIO_MODE_PULLUP |
                                                   /* Input function is not inverted */
                                                   IOCON_PIO_INV_DI |
                                                   /* Enables digital function */
                                                   IOCON_PIO_DIGITAL_EN |
                                                   /* Input filter disabled */
                                                   IOCON_PIO_INPFILT_OFF |
                                                   /* Standard mode, output slew rate control is enabled */
                                                   IOCON_PIO_SLEW_STANDARD |
                                                   /* Open drain is enabled */
                                                   IOCON_PIO_OPENDRAIN_EN);
              /* PORT1 PIN17 (coords: N12) is configured as FC8_RXD_SDA_MOSI */
              IOCON_PinMuxSet(IOCON, 2U, 0U, port2_pin0_config);

              const uint32_t port2_pin1_config = (/* Pin is configured as FC8_TXD_SCL_MISO */
                                                   IOCON_PIO_FUNC2 |
                                                   /* Selects pull-up function */
                                                   IOCON_PIO_MODE_PULLUP |
                                                   /* Input function is not inverted */
                                                   IOCON_PIO_INV_DI |
                                                   /* Enables digital function */
                                                   IOCON_PIO_DIGITAL_EN |
                                                   /* Input filter disabled */
                                                   IOCON_PIO_INPFILT_OFF |
                                                   /* Standard mode, output slew rate control is enabled */
                                                   IOCON_PIO_SLEW_STANDARD |
                                                   /* Open drain is enabled */
                                                   IOCON_PIO_OPENDRAIN_EN);
              /* PORT1 PIN18 (coords: D1) is configured as FC8_TXD_SCL_MISO */
              IOCON_PinMuxSet(IOCON, 2U, 1U, port2_pin1_config);

              //accelerometer IRQ
              const uint32_t port1_pin18_config = (/* Pin is configured as FC8_TXD_SCL_MISO */
             		 	 	 	 	 	 	 	  0 |
                                                   /* Selects pull-up function */
 												  IOCON_PIO_MODE_INACT |
                                                   /* Input function is not inverted */
                                                   IOCON_PIO_INV_DI |
                                                   /* Enables digital function */
 												  IOCON_PIO_DIGITAL_EN |
                                                   /* Input filter disabled */
                                                   IOCON_PIO_INPFILT_OFF |
                                                   /* Standard mode, output slew rate control is enabled */
                                                   IOCON_PIO_SLEW_STANDARD |
                                                   /* Open drain is enabled */
 												  IOCON_PIO_OPENDRAIN_DI);
              /* PORT1 PIN18 (coords: D1) is configured as FC8_TXD_SCL_MISO */
              IOCON_PinMuxSet(IOCON, 1U, 18U, port1_pin18_config);

             //accelerometer IRQ 2
              const uint32_t port0_pin30_config = (/* Pin is configured as FC8_TXD_SCL_MISO */
             		 	 	 	 	 	 	 	  IOCON_PIO_FUNC2 |
                                                   /* Selects pull-up function */
 												  IOCON_PIO_MODE_INACT |
                                                   /* Input function is not inverted */
                                                   IOCON_PIO_INV_DI |
                                                   /* Enables digital function */
 												  IOCON_PIO_DIGITAL_EN |
                                                   /* Input filter disabled */
                                                   IOCON_PIO_INPFILT_OFF |
                                                   /* Standard mode, output slew rate control is enabled */
                                                   IOCON_PIO_SLEW_STANDARD |
                                                   /* Open drain is enabled */
 												  IOCON_PIO_OPENDRAIN_DI);
              /* PORT1 PIN18 (coords: D1) is configured as FC8_TXD_SCL_MISO */
             IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);


             //ADC
             const uint32_t port1_pin0_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                                  0 | /*IOCON_PIO_FUNC1 */
                                                  /* No addition pin function */
                                                  IOCON_PIO_MODE_INACT |
                                                  /* Input function is not inverted */
                                                  IOCON_PIO_INV_DI |
                                                  /* Enables digital function */
                                                  0 | /*IOCON_PIO_DIGITAL_EN */
                                                  /* Input filter disabled */
                                                  IOCON_PIO_INPFILT_OFF |
                                                  /* Standard mode, output slew rate control is enabled */
                                                  IOCON_PIO_SLEW_STANDARD |
                                                  /* Open drain is disabled */
                                                  IOCON_PIO_OPENDRAIN_DI);
             /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
             IOCON_PinMuxSet(IOCON, 1U, 0U, port1_pin0_config);

             //PB INT
             const uint32_t port0_pin24_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                                  0 |
                                                  /* No addition pin function */
                                                  IOCON_PIO_MODE_INACT |
                                                  /* Input function is not inverted */
                                                  IOCON_PIO_INV_DI |
                                                  /* Enables digital function */
                                                  IOCON_PIO_DIGITAL_EN |
                                                  /* Input filter disabled */
                                                  IOCON_PIO_INPFILT_OFF |
                                                  /* Standard mode, output slew rate control is enabled */
                                                  IOCON_PIO_SLEW_STANDARD |
                                                  /* Open drain is disabled */
												  IOCON_PIO_OPENDRAIN_DI);
             /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
             IOCON_PinMuxSet(IOCON, 0U, 24U, port0_pin24_config);

             //PB Poweroff
             const uint32_t port1_pin22_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                                  IOCON_PIO_FUNC1 |
                                                  /* No addition pin function */
                                                  IOCON_PIO_MODE_INACT |
                                                  /* Input function is not inverted */
                                                  IOCON_PIO_INV_DI |
                                                  /* Enables digital function */
                                                  IOCON_PIO_DIGITAL_EN |
                                                  /* Input filter disabled */
                                                  IOCON_PIO_INPFILT_OFF |
                                                  /* Standard mode, output slew rate control is enabled */
                                                  IOCON_PIO_SLEW_STANDARD |
                                                  /* Open drain is disabled */
												  IOCON_PIO_OPENDRAIN_EN);
             /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
             IOCON_PinMuxSet(IOCON, 1U, 22U, port1_pin22_config);

}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
